<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Solicitud de acta de nacimiento</title>
<script type="text/javascript" src="jquery-1.3.1.min.js"></script>
<script type="text/javascript" src="jquery.autocomplete.js"></script>
<script type="text/javascript" src="jquery.select-autocomplete.js"></script>



<script language='javascript'>

var provincias_1=new Array('-','AGUASCALIENTES','ASIENTOS','CALVILLO','COSIO','JESUS MARIA','PABELLON DE ARTEAGA','RINCON DE ROMOS','SAN JOSE DE GRACIA','TEPEZALA','EL LLANO','SAN FRANCISCO DE LOS ROMO') 
var provincias_2=new Array("-",'ENSENADA','MEXICALI','TECATE','TIJUANA','PLAYAS DE ROSARITO') 
var provincias_3=new Array("-",'COMONDU','MULEGE','LA PAZ','LOS CABOS','LORETO') 
var provincias_4=new Array("-",'CALKINI','CAMPECHE','CARMEN','CHAMPOTON','HECELCHAKAN','HOPELCHEN','PALIZADA','TENABO','ESCARCEGA','CALAKMUL','CANDELARIA')
var provincias_5=new Array("-",'ABASOLO','ACUÑA','ALLENDE','ARTEAGA','CANDELA','CASTAÑOS','CUATROCIENEGAS','ESCOBEDO','FRANCISCO I. MADERO','FRONTERA','GENERAL CEPEDA','GUERRERO','HIDAL','JIMENEZ','JUAREZ','LAMADRID','MATAMOROS','MONCLOVA','MORELOS','MUZQUIZ','NADADORES','NAVA','OCAMPO','PARRAS','PIEDRAS NEGRAS','PROGRESO','RAMOS ARIZPE','SABINAS','SACRAMENTO','SALTILLO','SAN BUENAVENTURA','SAN JUAN DE SABINAS','SAN PEDRO','SIERRA MOJADA','TORREON','VIESCA','VILLA UNION','ZARAZA') 
var provincias_6=new Array("-",'ARMERIA','COLIMA','COMALA','COQUIMATLAN','CUAUHTEMOC','IXTLAHUACAN','MANZANILLO','MINATITLAN','TECOMAN','VILLA DE ALVAREZ') 
var provincias_7=new Array("-",'ACACOYAGUA','ACALA','ACAPETAHUA','ALTAMIRANO','AMATAN','AMATENAN DE LA FRONTERA','AMATENAN DEL VALLE','ANGEL ALBINO CORZO','ARRIAGA','BEJUCAL DE OCAMPO','BELLA VISTA','BERRIOZABAL','BOCHIL','EL BOSQUE','CACAHOATAN','CATAZAJA','CINTALAPA','COAPILLA','COMITAN DE DOMINGUEZ','LA CONCORDIA','COPAINALA','CHALCHIHUITAN','CHAMULA','CHANAL','CHAPULTENAN','CHENALHO','CHIAPA DE CORZO','CHIAPILLA','CHICOASEN','CHICOMUSELO','CHILON','ESCUINTLA','FRANCISCO LEON','FRONTERA COMALAPA','FRONTERA HIDAL','LA GRANDEZA','HUEHUETAN','HUIXTAN','HUITIUPAN','HUIXTLA','LA INDEPENDENCIA','IXHUATAN','IXTACOMITAN','IXTAPA','IXTAPANGAJOYA','JIQUIPILAS','JITOTOL','JUAREZ','LARRAINZAR','LA LIBERTAD','MAPASTEPEC','LAS MARGARITAS','MAZAPA DE MADERO','MAZATAN','METAPA','MITONTIC','MOTOZINTLA','NICOLAS RUIZ','OCOSIN','OCOTEPEC','OCOZOCOAUTLA DE ESPINOSA','OSTUACAN','OSUMACINTA','OXCHUC','PALENQUE','PANTELHO','PANTEPEC','PICHUCALCO','PIJIJIAPAN','EL PORVENIR','VILLA COMALTITLAN','PUEBLO NUEVO SOLISTAHUACAN','RAYON','REFORMA','LAS ROSAS','SABANILLA','SALTO DE AGUA','SAN CRISTOBAL DE LAS CASAS','SAN FERNANDO','SILTEPEC','SIMOJOVEL','SITALA','SOCOLTENAN','SOLOSUCHIAPA','SOYALO','SUCHIAPA','SUCHIATE','SUNUAPA','TAPACHULA','TAPALAPA','TAPILULA','TECPATAN','TENEJAPA','TEOPISCA','TILA','TONALA','TOTOLAPA','LA TRINITARIA','TUMBALA','TUXTLA GUTIERREZ','TUXTLA CHICO','TUZANTAN','TZIMOL','UNION JUAREZ','VENUSTIANO CARRANZA','VILLA CORZO','VILLAFLORES','YAJALON','SAN LUCAS','ZINACANTAN','SAN JUAN CANCUC','ALDAMA','BENEMERITO DE LAS AMERICAS','MARAVILLA TENEJAPA','MARQUES DE COMILLAS','MONTECRISTO DE GUERRERO','SAN ANDRES DURAZNAL','SANTIA EL PINAR')
var provincias_8=new Array("-",'AHUMADA','ALDAMA','ALLENDE','AQUILES SERDAN','ASCENSION','BACHINIVA','BALLEZA','BATOPILAS','BOCOYNA','BUENAVENTURA','CAMAR','CARICHI','CASAS GRANDES','CORONADO','COYAME DEL SOTOL','LA CRUZ','CUAUHTEMOC','CUSIHUIRIACHI','CHIHUAHUA','CHINIPAS','DELICIAS','DR. BELISARIO DOMINGUEZ','GALEANA','SANTA ISABEL','MEZ FARIAS','GRAN MORELOS','GUACHOCHI','GUADALUPE','GUADALUPE Y CALVO','GUAZAPARES','GUERRERO','HIDAL DEL PARRAL','HUEJOTITAN','IGNACIO ZARAZA','JANOS','JIMENEZ','JUAREZ','JULIMES','LOPEZ','MADERA','MAGUARICHI','MANUEL BENAVIDES','MATACHI','MATAMOROS','MEOQUI','MORELOS','MORIS','NAMIQUIPA','NONOAVA','NUEVO CASAS GRANDES','OCAMPO','OJINAGA','PRAXEDIS G. GUERRERO','RIVA PALACIO','ROSALES','ROSARIO','SAN FRANCISCO DE BORJA','SAN FRANCISCO DE CONCHOS','SAN FRANCISCO DEL ORO','SANTA BARBARA','SATEVO','SAUCILLO','TEMOSACHI','EL TULE','URIQUE','URUACHI','VALLE DE ZARAZA')
var provincias_9=new Array("-",'AZCAPOTZALCO','COYOACAN','CUAJIMALPA DE MORELOS','GUSTAVO A. MADERO','IZTACALCO','IZTAPALAPA','LA MAGDALENA CONTRERAS','MILPA ALTA','ALVARO OBREGON','TLAHUAC','TLALPAN','XOCHIMILCO','BENITO JUAREZ','CUAUHTEMOC','MIGUEL HIDALGO','VENUSTIANO CARRANZA') 
var provincias_10=new Array("-",'CANATLAN','CANELAS','CONETO DE COMONFORT','CUENCAME','DURAN','GRAL. SIMON BOIVAR','MEZ PALACIO','GUADALUPE VICTORIA','GUANACEVI','HIDAL','INDE','LERDO','MAPIMI','MEZQUITAL','NAZAS','NOMBRE DE DIOS','OCAMPO','EL ORO','OTAEZ','PANUCO DE CORONADO','PEÑON BLANCO','POANAS','PUEBLO NUEVO','RODEO','SAN BERNARDO','SAN DIMAS','SAN JUAN DE GUADALUPE','SAN JUAN DEL RIO','SAN LUIS DEL CORDERO','SAN PEDRO DEL GALLO','SANTA CLARA','SANTIA PAPASQUIARO','SUCHIL','TAMAZULA','TEPEHUANES','TLAHUALILO','TOPIA','VICENTE GUERRERO','NUEVO IDEAL')
var provincias_11=new Array("-",'ABASOLO','ACAMBARO','ALLENDE','APASEO EL ALTO','APASEO EL GRANDE','ATARJEA','CELAYA','MANUEL DOBLADO','COMONFORT','CORONEO','CORTAZAR','CUERAMARO','DOCTOR MORA','DOLORES HIDAL','GUANAJUATO','HUANIMARO','IRAPUATO','JARAL DEL PROGRESO','JERECUARO','LEON','MOROLEON','OCAMPO','PENJAMO','PUEBLO NUEVO','PURISIMA DEL RINCON','ROMITA','SALAMANCA','SALVATIERRA','SAN DIE DE LA UNION','SAN FELIPE','SAN FRANCISCO DEL RINCON','SAN JOSE ITURBIDE','SAN LUIS DE LA PAZ','SANTA CATARINA','SANTA CRUZ DE JUVENTINO ROSAS','SANTIA MARAVATIO','SILAO','TARANDACUAO','TARIMORO','TIERRA BLANCA','URIANGATO','VALLE DE SANTIA','VICTORIA','VILLAGRAN','XICHU','YURIRIA') 
var provincias_12=new Array("-",'ACAPULCO DE JUAREZ','AHUACUOTZIN','AJUCHITLAN DEL PROGRESO','ALCOZAUCA DE GUERRERO','ALPOYECA','APAXTLA','ARCELIA','ATENAN DEL RIO','ATLAMAJALCIN DEL MONTE','ATLIXTAC','ATOYAC DE ALVAREZ','AYUTLA DE LOS LIBRES','AZOYU','BENITO JUAREZ','BUENAVISTA DE CUELLAR','COAHUAYUTLA DE J. M. IZAZAGA','COCULA','COPALA','COPALILLO','COPANATOYAC','COYUCA DE BENITEZ','COYUCA DE CATALAN','CUAJINICUILAPA','CUALAC','CUAUTEPEC','CUETZALA DEL PROGRESO','CUTZAMALA DE PINZON','CHILAPA DE ALVAREZ','CHILPANCIN DE LOS BRAVO','FLORENCIO VILLARREAL','GENERAL CANUTO A. NERI','GENERAL HELIODORO CASTILLO','HUAMUXTITLAN','HUITZUCO DE LOS FIGUEROA','IGUALA DE LA INDEPENDENCIA','IGUALAPA','IXCATEOPAN DE CUAUHTEMOC','JOSE AZUETA','JUAN R. ESCUDERO','LEONARDO BRAVO','MALINALTEPEC','MARTIR DE CUILAPAN','METLATONOC','MOCHITLAN','OLINALA','OMETEPEC','PEDRO ASCENCIO ALQUISIRAS','PETATLAN','PILCAYA','PUNGARABATO','QUECHULTENAN','SAN LUIS ACATLAN','SAN MARCOS','SAN MIGUEL TOTOLAPAN','TAXCO DE ALARCON','TECOANAPA','TECPAN DE GALEANA','TELOLOAPAN','TEPECOACUILCO DE TRUJANO','TETIPAC','TIXTLA DE GUERRERO','TLACOACHISTLAHUACA','TLACOAPA','TLALCHAPA','TLALIXTAQUILLA DE MALDONADO','TLAPA DE COMONFORT','TLAPEHUALA','LA UNION DE I. MONTES DE OCA','XALPATLAHUAC','XOCHIHUEHUETLAN','XOCHISTLAHUACA','ZAPOTITLAN TABLAS','ZIRANDARO','ZITLALA','EDUARDO NERI','ACATEPEC')
var provincias_13=new Array("-",'ACATLAN','ACAXOCHITLAN','ACTOPAN','AGUA BLANCA DE ITURBIDE','AJACUBA','ALFAJAYUCAN','ALMOLOYA','APAN','EL ARENAL','ATITALAQUIA','ATLAPEXCO','ATOTONILCO EL GRANDE','ATOTONILCO DE TULA','CALNALI','CARDONAL','CUAUTEPEC DE HINOJOSA','CHAPANTON','CHAPULHUACAN','CHILCUAUTLA','ELOXOCHITLAN','EMILIANO ZAPATA','EPAZOYUCAN','FRANCISCO I. MADERO','HUASCA DE OCAMPO','HUAUTLA','HUAZALIN','HUEHUETLA','HUEJUTLA DE REYES','HUICHAPAN','IXMIQUILPAN','JACALA DE LEDEZMA','JALTOCAN','JUAREZ HIDAL','LOLOTLA','METEPEC','SAN AGUSTIN METZQUITITLAN','METZTITLAN','MINERAL DEL CHICO','MINERAL DEL MONTE','LA MISION','MIXQUIAHUALA DE JUAREZ','MOLAN DE ESCAMILLA','NICOLAS FLORES','NOPALA DE VILLAGRAN','OMITLAN DE JUAREZ','SAN FELIPE ORIZATLAN','PACULA','PACHUCA DE SOTO','PISAFLORES','PROGRESO DE OBREN','MINERAL DE LA REFORMA','SAN AGUSTIN TLAXIACA','SAN BARTOLO TUTOTEPEC','SAN SALVADOR','SANTIA DE ANAYA','SANTIA TULANTEPEC DE L. G.','SINGUILUCAN','TASQUILLO','TECOZAUTLA','TENAN DE DORIA','TEPEAPULCO','TEPEHUACAN DE GUERRERO','TEPEJI DEL RIO DE OCAMPO','TEPETITLAN','TETEPAN','VILLA DE TEZONTEPEC','TEZONTEPEC DE ALDAMA','TIANGUISTEN','TIZAYUCA','TLAHUELILPAN','TLAHUILTEPA','TLANALAPA','TLANCHINOL','TLAXCOAPAN','TOLCAYUCA','TULA DE ALLENDE','TULANCIN DE BRAVO','XOCHIATIPAN','XOCHICOATLAN','YAHUALICA','ZACUALTIPAN DE ANGELES','ZAPOTLAN DE JUAREZ','ZEMPOALA','ZIMAPAN') 
var provincias_14=new Array("-",'ACATIC','ACATLAN DE JUAREZ','AHUALULCO DE MERCADO','AMACUECA','AMATITAN','AMECA','SAN JUANITO DE ESCOBEDO','ARANDAS','EL ARENAL','ATEMAJAC DE BRIZUELA','ATEN','ATENGUILLO','ATOTONILCO EL ALTO','ATOYAC','AUTLAN DE NAVARRO','AYOTLAN','AYUTLA','LA BARCA','BOLAÑOS','CABO CORRIENTES','CASIMIRO CASTILLO','CIHUATLAN','ZAPOTLAN EL GRANDE','COCULA','COLOTLAN','CONCEPCION DE BUENOS AIRES','CUAUTITLAN DE GARCIA BARRAGAN','CUAUTLA','CUQUIO','CHAPALA','CHIMALTITAN','CHIQUILISTLAN','DELLADO','EJUTLA','ENCARNACION DE DIAZ','ETZATLAN','EL GRULLO','GUACHINAN','GUADALAJARA','HOSTOTIPAQUILLO','HUEJUCAR','HUEJUQUILLA EL ALTO','LA HUERTA','IXTLAHUACAN DE LOS MEMBRILLOS','IXTLAHUACAN DEL RIO','JALOSTOTITLAN','JAMAY','JESUS MARIA','JILOTLAN DE LOS DOLORES','JOCOTEPEC','JUANACATLAN','JUCHITLAN','LAS DE MORENO','EL LIMON','MAGDALENA','SANTA MARIA DEL ORO','LA MANZANILLA DE LA PAZ','MASCOTA','MAZAMITLA','MEXTICACAN','MEZQUITIC','MIXTLAN','OCOTLAN','OJUELOS DE JALISCO','PIHUAMO','PONCITLAN','PUERTO VALLARTA','VILLA PURIFICACION','QUITUPAN','EL SALTO','SAN CRISTOBAL DE LA BARRANCA','SAN DIE DE ALEJANDRIA','SAN JUAN DE LOS LAS','SAN JULIAN','SAN MARCOS','SAN MARTIN DE BOLAÑOS','SAN MARTIN DE HIDAL','SAN MIGUEL EL ALTO','MEZ FARIAS','SAN SEBASTIAN DEL OESTE','SANTA MARIA DE LOS ANGELES','SAYULA','TALA','TALPA DE ALLENDE','TAMAZULA DE RDIANO','TAPALPA','TECALITLAN','TECOLOTLAN','TECHALUTA DE MONTENEGRO','TENAMAXTLAN','TEOCALTICHE','TEOCUITATLAN DE CORONA','TEPATITLAN DE MORELOS','TEQUILA','TEUCHITLAN','TIZAPAN EL ALTO','TLAJOMULCO DE ZUÑIGA','TLAQUEPAQUE','TOLIMAN','TOMATLAN','TONALA','TONAYA','TONILA','TOTATICHE','TOTOTLAN','TUXCACUESCO','TUXCUECA','TUXPAN','UNION DE SAN ANTONIO','UNION DE TULA','VALLE DE GUADALUPE','VALLE DE JUAREZ','SAN GABRIEL','VILLA CORONA','VILLA GUERRERO','VILLA HIDAL','CAÑADAS DE OBREN','YAHUALICA DE NZALEZ GALLO','ZACOALCO DE TORRES','ZAPOPAN','ZAPOTILTIC','ZAPOTITLAN DE VADILLO','ZAPOTLAN DEL REY','ZAPOTLANEJO') 
var provincias_15=new Array("-",'ACAMBAY','ACOLMAN','ACULCO','ALMOLOYA DE ALQUISIRAS','ALMOLOYA DE JUAREZ','ALMOLOYA DEL RIO','AMANALCO','AMATEPEC','AMECAMECA','APAXCO','ATENCO','ATIZAPAN','ATIZAPAN DE ZARAZA','ATLACOMULCO','ATLAUTLA','AXAPUSCO','AYAPAN','CALIMAYA','CAPULHUAC','COACALCO DE BERRIOZABAL','COATEPEC HARINAS','COCOTITLAN','COYOTEPEC','CUAUTITLAN','CHALCO','CHAPA DE MOTA','CHAPULTEPEC','CHIAUTLA','CHICOLOAPAN','CHICONCUAC','CHIMALHUACAN','DONATO GUERRA','ECATEPEC DE MORELOS','ECATZIN','HUEHUETOCA','HUEYPOXTLA','HUIXQUILUCAN','ISIDRO FABELA','IXTAPALUCA','IXTAPAN DE LA SAL','IXTAPAN DEL ORO','IXTLAHUACA','XALATLACO','JALTENCO','JILOTEPEC','JILOTZIN','JIQUIPILCO','JOCOTITLAN','JOQUICIN','JUCHITEPEC','LERMA','MALINALCO','MELCHOR OCAMPO','METEPEC','MEXICALTZIN','MORELOS','NAUCALPAN DE JUAREZ','NEZAHUALCOYOTL','NEXTLALPAN','NICOLAS ROMERO','NOPALTEPEC','OCOYOACAC','OCUILAN','EL ORO','OTUMBA','OTZOLOAPAN','OTZOLOTEPEC','OZUMBA','PAPALOTLA','LA PAZ','POLOTITLAN','RAYON','SAN ANTONIO LA ISLA','SAN FELIPE DEL PROGRESO','SAN MARTIN DE LAS PIRAMIDES','SAN MATEO ATENCO','SAN SIMON DE GUERRERO','SANTO TOMAS','SOYANIQUILPAN DE JUAREZ','SULTEPEC','TECAMAC','TEJUPILCO','TEMAMATLA','TEMASCALAPA','TEMASCALCIN','TEMASCALTEPEC','TEMOAYA','TENANCIN','TENAN DEL AIRE','TENAN DEL VALLE','TEOLOYUCAN','TEOTIHUACAN','TEPETLAOXTOC','TEPETLIXPA','TEPOTZOTLAN','TEQUIXQUIAC','TEXCALTITLAN','TEXCALYACAC','TEXCOCO','TEZOYUCA','TIANGUISTENCO','TIMILPAN','TLALMANALCO','TLALNEPANTLA DE BAZ','TLATLAYA','TOLUCA','TONATICO','TULTEPEC','TULTITLAN','VALLE DE BRAVO','VILLA DE ALLENDE','VILLA DEL CARBON','VILLA GUERRERO','VILLA VICTORIA','XONACATLAN','ZACAZONAPAN','ZACUALPAN','ZINACANTEPEC','ZUMPAHUACAN','ZUMPAN','CUAUTITLAN IZCALLI','VALLE DE CHALCO SOLIDARIDAD','LUVIANOS','SAN JOSE DEL RINCON','TONANITLA') 
var provincias_16=new Array("-",'ACUITZIO','AGUILILLA','ALVARO OBREN','ANGAMACUTIRO','ANGANGUEO','APATZINGAN','APORO','AQUILA','ARIO','ARTEAGA','BRISEÑAS','BUENAVISTA','CARACUARO','COAHUAYANA','COALCOMAN DE VAZQUEZ PALLARES','COENEO','CONTEPEC','COPANDARO','COTIJA','CUITZEO','CHARAPAN','CHARO','CHAVINDA','CHERAN','CHILCHOTA','CHINICUILA','CHUCANDIRO','CHURINTZIO','CHURUMUCO','ECUANDUREO','EPITACIO HUERTA','ERONGARICUARO','GABRIEL ZAMORA','HIDAL','LA HUACANA','HUANDACAREO','HUANIQUEO','HUETAMO','HUIRAMBA','INDAPARAPEO','IRIMBO','IXTLAN','JACONA','JIMENEZ','JIQUILPAN','JUAREZ','JUNGAPEO','LAGUNILLAS','MADERO','MARAVATIO','MARCOS CASTELLANOS','LAZARO CARDENAS','MORELIA','MORELOS','MUGICA','NAHUATZEN','NOCUPETARO','NUEVO PARANGARICUTIRO','NUEVO URECHO','NUMARAN','OCAMPO','PAJACUARAN','PANINDICUARO','PARACUARO','PARACHO','PATZCUARO','PENJAMILLO','PERIBAN','LA PIEDAD','PUREPERO','PURUANDIRO','QUERENDARO','QUIROGA','COJUMATLAN DE REGULES','LOS REYES','SAHUAYO','SAN LUCAS','SANTA ANA MAYA','SALVADOR ESCALANTE','SENGUIO','SUSUPUATO','TACAMBARO','TANCITARO','TANGAMANDAPIO','TANGANCICUARO','TANHUATO','TARETAN','TARIMBARO','TEPALCATEPEC','TINGAMBATO','TINGUINDIN','TIQUICHEO DE NICOLAS ROMERO','TLALPUJAHUA','TLAZAZALCA','TOCUMBO','TUMBISCATIO','TURICATO','TUXPAN','TUZANTLA','TZINTZUNTZAN','TZITZIO','URUAPAN','VENUSTIANO CARRANZA','VILLAMAR','VISTA HERMOSA','YURECUARO','ZACAPU','ZAMORA','ZINAPARO','ZINAPECUARO','ZIRACUARETIRO','ZITACUARO','JOSE SIXTO VERDUZCO')
var provincias_17=new Array("-",'AMACUZAC','ATLATLAHUCAN','AXOCHIAPAN','AYALA','COATLAN DEL RIO','CUAUTLA','CUERNAVACA','EMILIANO ZAPATA','HUITZILAC','JANTETELCO','JIUTEPEC','JOJUTLA','JONACATEPEC','MAZATEPEC','MIACATLAN','OCUITUCO','PUENTE DE IXTLA','TEMIXCO','TEPALCIN','TEPOZTLAN','TETECALA','TETELA DEL VOLCAN','TLALNEPANTLA','TLALTIZAPAN','TLAQUILTENAN','TLAYACAPAN','TOTOLAPAN','XOCHITEPEC','YAUTEPEC','YECAPIXTLA','ZACATEPEC DE HIDAL','ZACUALPAN DE AMILPAS','TEMOAC') 
var provincias_18=new Array("-","Salta",'ACAPONETA','AHUACATLAN','AMATLAN DE CAÑAS','COMPOSTELA','HUAJICORI','IXTLAN DEL RIO','JALA','XALISCO','DEL NAYAR','ROSAMORADA','RUIZ','SAN BLAS','SAN PEDRO LAGUNILLAS','SANTA MARIA DEL ORO','SANTIA IXCUINTLA','TECUALA','TEPIC','TUXPAN','LA YESCA','BAHIA DE BANDERAS') 
var provincias_19=new Array("-",'ABASOLO','AGUALEGUAS','LOS ALDAMAS','ALLENDE','ANAHUAC','APODACA','ARAMBERRI','BUSTAMANTE','CADEREYTA JIMENEZ','CARMEN','CERRALVO','CIENEGA DE FLORES','CHINA','DR. ARROYO','DR.  COSS','DR. NZALEZ','GALEANA','GARCIA','SAN PEDRO GARZA GARCIA','GRAL. BRAVO','GRAL.  ESCOBEDO','GRAL.  TERAN','GRAL.  TREVIÑO','GRAL.  ZARAZA','GRAL.  ZUAZUA','GUADALUPE','LOS HERRERAS','HIGUERAS','HUALAHUISES','ITURBIDE','JUAREZ','LAMPAZOS DE NARANJO','LINARES','MARIN','MELCHOR OCAMPO','MIER Y NORIEGA','MINA','MONTEMORELOS','MONTERREY','PARAS','PESQUERIA','LOS RAMONES','RAYONES','SABINAS HIDAL','SALINAS VICTORIA','SAN NICOLAS DE LOS GARZA','HIDAL','SANTA CATARINA','SANTIA','VALLECILLO','VILLALDAMA') 

var provincias_20=new Array("-",'ABEJONES','ACATLAN DE PEREZ FIGUEROA','ASUNCION CACALOTEPEC','ASUNCION CUYOTEPEJI','ASUNCION IXTALTEPEC','ASUNCION NOCHIXTLAN','ASUNCION OCOTLAN','ASUNCION TLACOLULITA','AYOTZINTEPEC','EL BARRIO DE LA SOLEDAD','CALIHUALA','CANDELARIA LOXICHA','CIENEGA DE ZIMATLAN','CIUDAD IXTEPEC','COATECAS ALTAS','COICOYAN DE LAS FLORES','LA COMPAÑIA','CONCEPCION BUENAVISTA','CONCEPCION PAPALO','CONSTANCIA DEL ROSARIO','COSOLAPA','COSOLTEPEC','CUILAPAM DE GUERRERO','CUYAMECALCO VILLA DE ZARAZA','CHAHUITES','CHALCATON DE HIDAL','CHIQUIHUITLAN DE B. JUAREZ','EJUTLA DE CRESPO','ELOXOCHITLAN DE FLORES MAN','EL ESPINAL','TAMAZULAPAM DEL E. SANTO','FRESNILLO DE TRUJANO','GUADALUPE ETLA','GUADALUPE DE RAMIREZ','GUELATAO DE JUAREZ','GUEVEA DE HUMBOLDT','MESONES HIDAL','VILLA HIDAL','HUAJUAPAN DE LEON','HUAUTEPEC','HUAUTLA DE JIMENEZ','IXTLAN DE JUAREZ','JUCHITAN DE ZARAZA','LOMA BONITA','MAGDALENA APASCO','MAGDALENA JALTEPEC','SANTA MAGDALENA JICOTLAN','MAGDALENA MIXTEPEC','MAGDALENA OCOTLAN','MAGDALENA PEÑASCO','MAGDALENA TEITIPAC','MAGDALENA TEQUISISTLAN','MAGDALENA TLACOTEPEC','MAGDALENA ZAHUATLAN','MARISCALA DE JUAREZ','MARTIRES DE TACUBAYA','MATIAS ROMERO AVENDAÑO','MAZATLAN VILLA DE FLORES','MIAHUATLAN DE PORFIRIO DIAZ','MIXISTLAN DE LA REFORMA','MONJAS','NATIVIDAD','NAZARENO ETLA','NEJAPA DE MADERO','IXPANTEPEC NIEVES','SANTIA NILTEPEC','OAXACA DE JUAREZ','OCOTLAN DE MORELOS','LA PE','PINOTEPA DE DON LUIS','PLUMA HIDAL','SAN JOSE DEL PROGRESO','PUTLA VILLA DE GUERRERO','SANTA CATARINA QUIOQUITANI','REFORMA DE PINEDA','LA REFORMA','REYES ETLA','ROJAS DE CUAUHTEMOC','SALINA CRUZ','SAN AGUSTIN AMATEN','SAN AGUSTIN ATENAN','SAN AGUSTIN CHAYUCO','SAN AGUSTIN DE LAS JUNTAS','SAN AGUSTIN ETLA','SAN AGUSTIN LOXICHA','SAN AGUSTIN TLACOTEPEC','SAN AGUSTIN YATARENI','SAN ANDRES CABECERA NUEVA','SAN ANDRES DINICUITI','SAN ANDRES HUAXPALTEPEC','SAN ANDRES HUAYAPAM','SAN ANDRES IXTLAHUACA','SAN ANDRES LAGUNAS','SAN ANDRES NUXIÑO','SAN ANDRES PAXTLAN','SAN ANDRES SINAXTLA','SAN ANDRES SOLAGA','SAN ANDRES TEOTILALPAM','SAN ANDRES TEPETLAPA','SAN ANDRES YAA','SAN ANDRES ZABACHE','SAN ANDRES ZAUTLA','SAN ANTONINO CASTILLO VELASCO','SAN ANTONINO EL ALTO','SAN ANTONINO MONTE VERDE','SAN ANTONIO ACUTLA','SAN ANTONIO DE LA CAL','SAN ANTONIO HUITEPEC','SAN ANTONIO NANAHUATIPAM','SAN ANTONIO SINICAHUA','SAN ANTONIO TEPETLAPA','SAN BALTAZAR CHICHICAPAM','SAN BALTAZAR LOXICHA','SAN BALTAZAR YATZACHI EL BAJO','SAN BARTOLO COYOTEPEC','SAN BARTOLOME AYAUTLA','SAN BARTOLOME LOXICHA','SAN BARTOLOME QUIALANA','SAN BARTOLOME YUCUAÑE','SAN BARTOLOME ZOOCHO','SAN BARTOLO SOYALTEPEC','SAN BARTOLO YAUTEPEC','SAN BERNARDO MIXTEPEC','SAN BLAS ATEMPA','SAN CARLOS YAUTEPEC','SAN CRISTOBAL AMATLAN','SAN CRISTOBAL AMOLTEPEC','SAN CRISTOBAL LACHIRIOAG','SAN CRISTOBAL SUCHIXTLAHUACA','SAN DIONISIO DEL MAR','SAN DIONISIO OCOTEPEC','SAN DIONISIO OCOTLAN','SAN ESTEBAN ATATLAHUCA','SAN FELIPE JALAPA DE DIAZ','SAN FELIPE TEJALAPAM','SAN FELIPE USILA','SAN FRANCISCO CAHUACUA','SAN FRANCISCO CAJONOS','SAN FRANCISCO CHAPULAPA','SAN FRANCISCO CHINDUA','SAN FRANCISCO DEL MAR','SAN FRANCISCO HUEHUETLAN','SAN FRANCISCO IXHUATAN','SAN FRANCISCO JALTEPETON','SAN FRANCISCO LACHILO','SAN FRANCISCO LOGUECHE','SAN FRANCISCO NUXAÑO','SAN FRANCISCO OZOLOTEPEC','SAN FRANCISCO SOLA','SAN FRANCISCO TELIXTLAHUACA','SAN FRANCISCO TEOPAN','SAN FRANCISCO TLAPANCIN','SAN GABRIEL MIXTEPEC','SAN ILDEFONSO AMATLAN','SAN ILDEFONSO SOLA','SAN ILDEFONSO VILLA ALTA','SAN JACINTO AMILPAS','SAN JACINTO TLACOTEPEC','SAN JERONIMO COATLAN','SAN JERONIMO SILACAYOAPILLA','SAN JERONIMO SOSOLA','SAN JERONIMO TAVICHE','SAN JERONIMO TECOATL','SAN JORGE NUCHITA','SAN JOSE AYUQUILA','SAN JOSE CHILTEPEC','SAN JOSE DEL PEÑASCO','SAN JOSE ESTANCIA GRANDE','SAN JOSE INDEPENDENCIA','SAN JOSE LACHIGUIRI','SAN JOSE TENAN','SAN JUAN ACHIUTLA','SAN JUAN ATEPEC','ANIMAS TRUJANO','SAN JUAN BAUTISTA ATATLAHUCA','S. J. BAUTISTA COIXTLAHUACA ','SAN JUAN BAUTISTA CUICATLAN','SAN JUAN BAUTISTA GUELACHE','SAN JUAN BAUTISTA JAYACATLAN','SAN JUAN BAUTISTA LO DE SOTO','SAN JUAN BAUTISTA SUCHITEPEC','S. J BAUTISTA TLACOATZINTEPEC','S. J. BAUTISTA TLACHICHILCO','SAN JUAN BAUTISTA TUXTEPEC','SAN JUAN CACAHUATEPEC','SAN JUAN CIENEGUILLA','SAN JUAN COATZOSPAM','SAN JUAN COLORADO','SAN JUAN COMALTEPEC','SAN JUAN COTZOCON','SAN JUAN CHICOMEZUCHIL','SAN JUAN CHILATECA','SAN JUAN DEL ESTADO','SAN JUAN DEL RIO','SAN JUAN DIUXI','SAN JUAN EVANGELISTA ANALCO','SAN JUAN GUELAVIA','SAN JUAN GUICHICOVI','SAN JUAN IHUALTEPEC','SAN JUAN JUQUILA MIXES','SAN JUAN JUQUILA VIJANOS','SAN JUAN LACHAO','SAN JUAN LACHIGALLA','SAN JUAN LAJARCIA','SAN JUAN LALANA','SAN JUAN DE LOS CUES','SAN JUAN MAZATLAN','SAN JUAN MIXTEPEC - D. 08 –','SAN JUAN MIXTEPEC - D. 26 –','SAN JUAN ÑUMI','SAN JUAN OZOLOTEPEC','SAN JUAN PETLAPA','SAN JUAN QUIAHIJE','SAN JUAN QUIOTEPEC','SAN JUAN SAYULTEPEC','SAN JUAN TABAA','SAN JUAN TAMAZOLA','SAN JUAN TEITA','SAN JUAN TEITIPAC','SAN JUAN TEPEUXILA','SAN JUAN TEPOSCOLULA','SAN JUAN YAEE','SAN JUAN YATZONA','SAN JUAN YUCUITA','SAN LORENZO','SAN LORENZO ALBARRADAS','SAN LORENZO CACAOTEPEC','SAN LORENZO CUAUNECUILTITLA','SAN LORENZO TEXMELUCAN','SAN LORENZO VICTORIA','SAN LUCAS CAMOTLAN','SAN LUCAS OJITLAN','SAN LUCAS QUIAVINI','SAN LUCAS ZOQUIAPAM','SAN LUIS AMATLAN','SAN MARCIAL OZOLOTEPEC','SAN MARCOS ARTEAGA','SAN MARTIN DE LOS CANSECOS','SAN MARTIN HUAMELULPAM','SAN MARTIN ITUNYOSO','SAN MARTIN LACHILA','SAN MARTIN PERAS','SAN MARTIN TILCAJETE','SAN MARTIN TOXPALAN','SAN MARTIN ZACATEPEC','SAN MATEO CAJONOS','CAPULALPAM DE MENDEZ','SAN MATEO DEL MAR','SAN MATEO YOLOXOCHITLAN','SAN MATEO ETLATON','SAN MATEO NEJAPAM','SAN MATEO PEÑASCO','SAN MATEO PIÑAS','SAN MATEO RIO HONDO','SAN MATEO SINDIHUI','SAN MATEO TLAPILTEPEC','SAN MELCHOR BETAZA','SAN MIGUEL ACHIUTLA','SAN MIGUEL AHUEHUETITLAN','SAN MIGUEL ALOAPAM','SAN MIGUEL AMATITLAN','SAN MIGUEL AMATLAN','SAN MIGUEL COATLAN','SAN MIGUEL CHICAHUA','SAN MIGUEL CHIMALAPA','SAN MIGUEL DEL PUERTO','SAN MIGUEL DEL RIO','SAN MIGUEL EJUTLA','SAN MIGUEL EL GRANDE','SAN MIGUEL HUAUTLA','SAN MIGUEL MIXTEPEC','SAN MIGUEL PANIXTLAHUACA','SAN MIGUEL PERAS','SAN MIGUEL PIEDRAS','SAN MIGUEL QUETZALTEPEC','SAN MIGUEL SANTA FLOR','VILLA SOLA DE VEGA','SAN MIGUEL SOYALTEPEC','SAN MIGUEL SUCHIXTEPEC','VILLA TALEA DE CASTRO','SAN MIGUEL TECOMATLAN','SAN MIGUEL TENAN','SAN MIGUEL TEQUIXTEPEC','SAN MIGUEL TILQUIAPAM','SAN MIGUEL TLACAMAMA','SAN MIGUEL TLACOTEPEC','SAN MIGUEL TULANCIN','SAN MIGUEL YOTAO','SAN NICOLAS','SAN NICOLAS HIDAL','SAN PABLO COATLAN','SAN PABLO CUATRO VENADOS','SAN PABLO ETLA','SAN PABLO HUITZO','SAN PABLO HUIXTEPEC','SAN PABLO MACUILTIANGUIS','SAN PABLO TIJALTEPEC','SAN PABLO VILLA DE MITLA','SAN PABLO YAGANIZA','SAN PEDRO AMUZS','SAN PEDRO APOSTOL','SAN PEDRO ATOYAC','SAN PEDRO CAJONOS','S. PEDRO COXCALTEPEC CANTAROS','SAN PEDRO COMITANCILLO','SAN PEDRO EL ALTO','SAN PEDRO HUAMELULA','SAN PEDRO HUILOTEPEC','SAN PEDRO IXCATLAN','SAN PEDRO IXTLAHUACA','SAN PEDRO JALTEPETON','SAN PEDRO JICAYAN','SAN PEDRO JOCOTIPAC','SAN PEDRO JUCHATEN','SAN PEDRO MARTIR','SAN PEDRO MARTIR QUIECHAPA','SAN PEDRO MARTIR YUCUXACO','SAN PEDRO MIXTEPEC - D. 22 –','SAN PEDRO MIXTEPEC - D. 26 –','SAN PEDRO MOLINOS','SAN PEDRO NOPALA','SAN PEDRO OCOPETATILLO','SAN PEDRO OCOTEPEC','SAN PEDRO POCHUTLA','SAN PEDRO QUIATONI','SAN PEDRO SOCHIAPAM','SAN PEDRO TAPANATEPEC','SAN PEDRO TAVICHE','SAN PEDRO TEOZACOALCO','SAN PEDRO TEUTILA','SAN PEDRO TIDAA','SAN PEDRO TOPILTEPEC','SAN PEDRO TOTOLAPA','VILLA DE TUTUTEPEC DE M. O.','SAN PEDRO YANERI','SAN PEDRO YOLOX','SAN PEDRO Y SAN PABLO AYUTLA','VILLA DE ETLA','S PEDRO Y S PABLO TEPOSCOLULA','S PEDRO Y S PABLO TEQUIXTEPEC','SAN PEDRO YUCUNAMA','SAN RAYMUNDO JALPAN','SAN SEBASTIAN ABASOLO','SAN SEBASTIAN COATLAN','SAN SEBASTIAN IXCAPA','SAN SEBASTIAN NICANANDUTA','SAN SEBASTIAN RIO HONDO','SAN SEBASTIAN TECOMAXTLAHUACA','SAN SEBASTIAN TEITIPAC','SAN SEBASTIAN TUTLA','SAN SIMON ALMOLONGAS','SAN SIMON ZAHUATLAN','SANTA ANA','SANTA ANA ATEIXTLAHUACA','SANTA ANA CUAUHTEMOC','SANTA ANA DEL VALLE','SANTA ANA TAVELA','SANTA ANA TLAPACOYAN','SANTA ANA YARENI','SANTA ANA ZEGACHE','SANTA CATALINA QUIERI','SANTA CATARINA CUIXTLA','SANTA CATARINA IXTEPEJI','SANTA CATARINA JUQUILA','SANTA CATARINA LACHATAO','SANTA CATARINA LOXICHA','SANTA CATARINA MECHOACAN','SANTA CATARINA MINAS','SANTA CATARINA QUIANE','SANTA CATARINA TAYATA','SANTA CATARINA TICUA','SANTA CATARINA YOSONOTU','SANTA CATARINA ZAPOQUILA','SANTA CRUZ ACATEPEC','SANTA CRUZ AMILPAS','SANTA CRUZ DE BRAVO','SANTA CRUZ ITUNDUJIA','SANTA CRUZ MIXTEPEC','SANTA CRUZ NUNDACO','SANTA CRUZ PAPALUTLA','SANTA CRUZ TACACHE DE MINA','SANTA CRUZ TACAHUA','SANTA CRUZ TAYATA','SANTA CRUZ XITLA','SANTA CRUZ XOXOCOTLAN','SANTA CRUZ ZENZONTEPEC','SANTA GERTRUDIS','SANTA INES DEL MONTE','SANTA INES YATZECHE','SANTA LUCIA DEL CAMINO','SANTA LUCIA MIAHUATLAN','SANTA LUCIA MONTEVERDE','SANTA LUCIA OCOTLAN','SANTA MARIA ALOTEPEC','SANTA MARIA APAZCO','SANTA MARIA LA ASUNCION','HEROICA CIUDAD DE TLAXIACO','AYOQUEZCO DE ALDAMA','SANTA MARIA ATZOMPA','SANTA MARIA CAMOTLAN','SANTA MARIA COLOTEPEC','SANTA MARIA CORTIJO','SANTA MARIA COYOTEPEC','SANTA MARIA CHACHOAPAM','VILLA DE CHILAPA DE DIAZ','SANTA MARIA CHILCHOTLA','SANTA MARIA CHIMALAPA','SANTA MARIA DEL ROSARIO','SANTA MARIA DEL TULE','SANTA MARIA ECATEPEC','SANTA MARIA GUELACE','SANTA MARIA GUIENAGATI','SANTA MARIA HUATULCO','SANTA MARIA HUAZOLOTITLAN','SANTA MARIA IPALAPA','SANTA MARIA IXCATLAN','SANTA MARIA JACATEPEC','STA. MARIA JALAPA DEL MARQUES','SANTA MARIA JALTIANGUIS','SANTA MARIA LACHIXIO','SANTA MARIA MIXTEQUILLA','SANTA MARIA NATIVITAS','SANTA MARIA NDUAYACO','SANTA MARIA OZOLOTEPEC','SANTA MARIA PAPALO','SANTA MARIA PEÑOLES','SANTA MARIA PETAPA','SANTA MARIA QUIELANI','SANTA MARIA SOLA','SANTA MARIA TATALTEPEC','SANTA MARIA TECOMAVACA','SANTA MARIA TEMAXCALAPA','SANTA MARIA TEMAXCALTEPEC','SANTA MARIA TEOPOXCO','SANTA MARIA TEPANTLALI','SANTA MARIA TEXCATITLAN','SANTA MARIA TLAHUITOLTEPEC','SANTA MARIA TLALIXTAC','SANTA MARIA TONAMECA','SANTA MARIA TOTOLAPILLA','SANTA MARIA XADANI','SANTA MARIA YALINA','SANTA MARIA YAVESIA','SANTA MARIA YOLOTEPEC','SANTA MARIA YOSOYUA','SANTA MARIA YUCUHITI','SANTA MARIA ZACATEPEC','SANTA MARIA ZANIZA','SANTA MARIA ZOQUITLAN','SANTIA AMOLTEPEC','SANTIA APOALA','SANTIA APOSTOL','SANTIA ASTATA','SANTIA ATITLAN','SANTIA AYUQUILILLA','SANTIA CACALOXTEPEC','SANTIA CAMOTLAN','SANTIA COMALTEPEC','SANTIA CHAZUMBA','SANTIA CHOAPAM','SANTIA DEL RIO','SANTIA HUAJOLOTITLAN','SANTIA HUAUCLILLA','SANTIA IHUITLAN PLUMAS','SANTIA IXCUINTEPEC','SANTIA IXTAYUTLA','SANTIA JAMILTEPEC','SANTIA JOCOTEPEC','SANTIA JUXTLAHUACA','SANTIA LACHIGUIRI','SANTIA LALOPA','SANTIA LAOLLAGA','SANTIA LAXOPA','SANTIA LLANO GRANDE','SANTIA MATATLAN','SANTIA MILTEPEC','SANTIA MINAS','SANTIA NACALTEPEC','SANTIA NEJAPILLA','SANTIA NUNDICHE','SANTIA NUYOO','SANTIA PINOTEPA NACIONAL','SANTIA SUCHILQUITON','SANTIA TAMAZOLA','SANTIA TAPEXTLA','VILLA TEJUPAM DE LA UNION','SANTIA TENAN','SANTIA TEPETLAPA','SANTIA TETEPEC','SANTIA TEXCALCIN','SANTIA TEXTITLAN','SANTIA TILANTON','SANTIA TILLO','SANTIA TLAZOYALTEPEC','SANTIA XANICA','SANTIA XIACUI','SANTIA YAITEPEC','SANTIA YAVEO','SANTIA YOLOMECATL','SANTIA YOSONDUA','SANTIA YUCUYACHI','SANTIA ZACATEPEC','SANTIA ZOOCHILA','NUEVO ZOQUIAPAM','SANTO DOMIN INGENIO','SANTO DOMIN ALBARRADAS','SANTO DOMIN ARMENTA','SANTO DOMIN CHIHUITAN','SANTO DOMIN DE MORELOS','SANTO DOMIN IXCATLAN','SANTO DOMIN NUXAA','SANTO DOMIN OZOLOTEPEC','SANTO DOMIN PETAPA','SANTO DOMIN ROAYAGA','SANTO DOMIN TEHUANTEPEC','SANTO DOMIN TEOJOMULCO','SANTO DOMIN TEPUXTEPEC','SANTO DOMIN TLATAYAPAM','SANTO DOMIN TOMALTEPEC','SANTO DOMIN TONALA','SANTO DOMIN TONALTEPEC','SANTO DOMIN XAGACIA','SANTO DOMIN YANHUITLAN','SANTO DOMIN YODOHINO','SANTO DOMIN ZANATEPEC','SANTOS REYES NOPALA','SANTOS REYES PAPALO','SANTOS REYES TEPEJILLO','SANTOS REYES YUCUNA','SANTO TOMAS JALIEZA','SANTO TOMAS MAZALTEPEC','SANTO TOMAS OCOTEPEC','SANTO TOMAS TAMAZULAPAN','SAN VICENTE COATLAN','SAN VICENTE LACHIXIO','SAN VICENTE NUÑU','SILACAYOAPAM','SITIO DE XITLAPEHUA','SOLEDAD ETLA','V. TAMAZULAPAM DEL PROGRESO','TANETZE DE ZARAZA','TANICHE','TATALTEPEC DE VALDES','TEOCOCUILCO DE MARCOS PEREZ','TEOTITLAN DE FLORES MAN','TEOTITLAN DEL VALLE','TEOTON','TEPELMEME VILLA DE MORELOS','TEZOATLAN DE SEGURA Y LUNA','SAN JERONIMO TLACOCHAHUAYA','TLACOLULA DE MATAMOROS','TLACOTEPEC PLUMAS','TLALIXTAC DE CABRERA','TOTONTEPEC VILLA DE MORELOS','TRINIDAD ZAACHILA','LA TRINIDAD VISTA HERMOSA','UNION HIDAL','VALERIO TRUJANO','S. J. BAUTISTA VALLE NACIONAL','VILLA DIAZ ORDAZ','YAXE','MAGDALENA YODOCONO DE P. DIAZ','YOGANA','YUTANDUCHI DE GUERRERO','VILLA DE ZAACHILA','ZAPOTITLAN DEL RIO','ZAPOTITLAN LAGUNAS','ZAPOTITLAN PALMAS','SANTA INES DE ZARAZA','ZIMATLAN DE ALVAREZ')
var provincias_21=new Array("-",'ACAJETE','ACATENO','ACATLAN','ACATZIN','ACTEOPAN','AHUACATLAN','AHUATLAN','AHUAZOTEPEC','AHUEHUETITLA','AJALPAN','ALBINO ZERTUCHE','ALJOJUCA','ALTEPEXI','AMIXTLAN','AMOZOC','AQUIXTLA','ATEMPAN','ATEXCAL','ATLIXCO','ATOYATEMPAN','ATZALA','ATZITZIHUACAN','ATZITZINTLA','AXUTLA','AYOTOXCO DE GUERRERO','CALPAN','CALTEPEC','CAMOCUAUTLA','CAXHUACAN','COATEPEC','COATZIN','COHETZALA','COHUECAN','CORONAN','COXCATLAN','COYOMEAPAN','COYOTEPEC','CUAPIAXTLA DE MADERO','CUAUTEMPAN','CUAUTINCHAN','CUAUTLANCIN','CUAYUCA DE ANDRADE','CUETZALAN DEL PROGRESO','CUYOACO','CHALCHICOMULA DE SESMA','CHAPULCO','CHIAUTLA','CHIAUTZIN','CHICONCUAUTLA','CHICHIQUILA','CHIETLA','CHIGMECATITLAN','CHIGNAHUAPAN','CHIGNAUTLA','CHILA','CHILA DE LA SAL','HONEY','CHILCHOTLA','CHINANTLA','DOMIN ARENAS','ELOXOCHITLAN','EPATLAN','ESPERANZA','FRANCISCO Z. MENA','GENERAL FELIPE ¾NGELES','GUADALUPE','GUADALUPE VICTORIA','HERMENEGILDO GALEANA','HUAQUECHULA','HUATLATLAUCA','HUAUCHINAN','HUEHUETLA','HUEHUETLAN EL CHICO','HUEJOTZIN','HUEYAPAN','HUEYTAMALCO','HUEYTLALPAN','HUITZILAN DE SERDAN','HUITZILTEPEC','ATLEQUIZAYAN','IXCAMILPA DE GUERRERO','IXCAQUIXTLA','IXTACAMAXTITLAN','IXTEPEC','IZUCAR DE MATAMOROS','JALPAN','JOLALPAN','JONOTLA','JOPALA','JUAN C. BONILLA','JUAN GALINDO','JUAN N. MENDEZ','LAFRAGUA','LIBRES','LA MAGDALENA TLATLAUQUITEPEC','MAZAPILTEPEC DE JUAREZ','MIXTLA','MOLCAXAC','CAÑADA MORELOS','NAUPAN','NAUZONTLA','NEALTICAN','NICOLAS BRAVO','NOPALUCAN','OCOTEPEC','OCOYUCAN','OLINTLA','ORIENTAL','PAHUATLAN','PALMAR DE BRAVO','PANTEPEC','PETLALCIN','PIAXTLA','PUEBLA','QUECHOLAC','QUIMIXTLAN','RAFAEL LARA GRAJALES','LOS REYES DE JUAREZ','SAN ANDRES CHOLULA','SAN ANTONIO CAÑADA','S. D. LA MESA TOCHIMILTZIN','SAN FELIPE TEOTLALCIN','SAN FELIPE TEPATLAN','SAN GABRIEL CHILAC','SAN GRERIO ATZOMPA','SAN JERONIMO TECUANIPAN','SAN JERONIMO XAYACATLAN','SAN JOSE CHIAPA','SAN JOSE MIAHUATLAN','SAN JUAN ATENCO','SAN JUAN ATZOMPA','SAN MARTIN TEXMELUCAN','SAN MARTIN TOTOLTEPEC','SAN MATIAS TLALANCALECA','SAN MIGUEL IXITLAN','SAN MIGUEL XOXTLA','SAN NICOLAS BUENOS AIRES','SAN NICOLAS DE LOS RANCHOS','SAN PABLO ANICANO','SAN PEDRO CHOLULA','SAN PEDRO YELOIXTLAHUACA','SAN SALVADOR EL SECO','SAN SALVADOR EL VERDE','SAN SALVADOR HUIXCOLOTLA','SAN SEBASTIAN TLACOTEPEC','SANTA CATARINA TLALTEMPAN','SANTA INES AHUATEMPAN','SANTA ISABEL CHOLULA','SANTIA MIAHUATLAN','HUEHUETLAN EL GRANDE','SANTO TOMAS HUEYOTLIPAN','SOLTEPEC','TECALI DE HERRERA','TECAMACHALCO','TECOMATLAN','TEHUACAN','TEHUITZIN','TENAMPULCO','TEOPANTLAN','TEOTLALCO','TEPANCO DE LOPEZ','TEPAN DE RODRIGUEZ','TEPATLAXCO DE HIDAL','TEPEACA','TEPEMAXALCO','TEPEOJUMA','TEPETZINTLA','TEPEXCO','TEPEXI DE RODRIGUEZ','TEPEYAHUALCO','TEPEYAHUALCO DE CUAUHTEMOC','TETELA DE OCAMPO','TETELES DE AVILA CASTILLO','TEZIUTLAN','TIANGUISMANALCO','TILAPA','TLACOTEPEC DE BENITO JUAREZ','TLACUILOTEPEC','TLACHICHUCA','TLAHUAPAN','TLALTENAN','TLANEPANTLA','TLAOLA','TLAPACOYA','TLAPANALA','TLATLAUQUITEPEC','TLAXCO','TOCHIMILCO','TOCHTEPEC','TOTOLTEPEC DE GUERRERO','TULCIN','TUZAMAPAN DE GALEANA','TZICATLACOYAN','VENUSTIANO CARRANZA','VICENTE GUERRERO','XAYACATLAN DE BRAVO','XICOTEPEC','XICOTLAN','XIUTETELCO','XOCHIAPULCO','XOCHILTEPEC','XOCHITLAN DE VICENTE SUAREZ','XOCHITLAN TODOS SANTOS','YAONAHUAC','YEHUALTEPEC','ZACAPALA','ZACAPOAXTLA','ZACATLAN','ZAPOTITLAN','ZAPOTITLAN DE MENDEZ','ZARAZA','ZAUTLA','ZIHUATEUTLA','ZINACATEPEC','ZONZOTLA','ZOQUIAPAN','ZOQUITLAN') 
var provincias_22=new Array("-",'AMEALCO DE BONFIL','PINAL DE AMOLES','ARROYO SECO','CADEREYTA DE MONTES','COLON','CORREGIDORA','EZEQUIEL MONTES','HUIMILPAN','JALPAN DE SERRA','LANDA DE MATAMOROS','EL MARQUES','PEDRO ESCOBEDO','PEÑAMILLER','QUERETARO','SAN JOAQUIN','SAN JUAN DEL RIO','TEQUISQUIAPAN','TOLIMAN')
var provincias_23=new Array("-",'COZUMEL','FELIPE CARRILLO PUERTO','ISLA MUJERES','OTHON P. BLANCO','BENITO JUAREZ','JOSE MARIA MORELOS','LAZARO CARDENAS','SOLIDARIDAD') 
var provincias_24=new Array("-",'AHUALULCO','ALAQUINES','AQUISMON','ARMADILLO DE LOS INFANTE','CARDENAS','CATORCE','CEDRAL','CERRITOS','CERRO DE SAN PEDRO','CIUDAD DEL MAIZ','CIUDAD FERNANDEZ','TANCANHUITZ','CIUDAD VALLES','COXCATLAN','CHARCAS','EBANO','GUADALCAZAR','HUEHUETLAN','LAGUNILLAS','MATEHUALA','MEXQUITIC DE CARMONA','MOCTEZUMA','RAYON','RIOVERDE','SALINAS','SAN ANTONIO','SAN CIRO DE ACOSTA','SAN LUIS POTOSI','SAN MARTIN CHALCHICUAUTLA','SAN NICOLAS TOLENTINO','SANTA CATARINA','SANTA MARIA DEL RIO','SANTO DOMIN','SAN VICENTE TANCUAYALAB','SOLEDAD DE GRACIANO SANCHEZ','TAMASOPO','TAMAZUNCHALE','TAMPACAN','TAMPAMOLON CORONA','TAMUIN','TANLAJAS','TANQUIAN DE ESCOBEDO','TIERRA NUEVA','VANEGAS','VENADO','VILLA DE ARRIAGA','VILLA DE GUADALUPE','VILLA DE LA PAZ','VILLA DE RAMOS','VILLA DE REYES','VILLA HIDAL','VILLA JUAREZ','AXTLA DE TERRAZAS','XILITLA','ZARAZA','VILLA DE ARISTA','MATLAPA','EL NARANJO')
var provincias_25=new Array("-",'AHOME','ANSTURA','BADIRAGUATO','CONCORDIA','COSALA','CULIACAN','CHOIX','ELOTA','ESCUINAPA','EL FUERTE','GUASAVE','MAZATLAN','MOCORITO','ROSARIO','SALVADOR ALVARADO','SAN IGNACIO','SINALOA','NAVOLATO') 
var provincias_26=new Array("-",'ACONCHI','AGUA PRIETA','ALAMOS','ALTAR','ARIVECHI','ARIZPE','ATIL','BACADEHUACHI','BACANORA','BACERAC','BACOACHI','BACUM','BANAMICHI','BAVIACORA','BAVISPE','BENJAMIN HILL','CABORCA','CAJEME','CANANEA','CARBO','LA COLORADA','CUCURPE','CUMPAS','DIVISADEROS','EMPALME','ETCHOJOA','FRONTERAS','GRANADOS','GUAYMAS','HERMOSILLO','HUACHINERA','HUASABAS','HUATABAMPO','HUEPAC','IMURIS','MAGDALENA','MAZATAN','MOCTEZUMA','NACO','NACORI CHICO','NACOZARI DE GARCIA','NAVOJOA','NOGALES','ONAVAS','OPODEPE','OQUITOA','PITIQUITO','PUERTO PEÑASCO','QUIRIE','RAYON','ROSARIO','SAHUARIPA','SAN FELIPE DE JESUS','SAN JAVIER','SAN LUIS RIO COLORADO','SAN MIGUEL DE HORCASITAS','SAN PEDRO DE LA CUEVA','SANTA ANA','SANTA CRUZ','SARIC','SOYOPA','SUAQUI GRANDE','TEPACHE','TRINCHERAS','TUBUTAMA','URES','VILLA HIDAL','VILLA PESQUEIRA','YECORA','GENERAL PLUTARCO ELIAS CALLES','BENITO JUAREZ','SAN IGNACIO RIO MUERTO') 

var provincias_27=new Array("-",'BALANCAN','CARDENAS','CENTLA','CENTRO','COMALCALCO','CUNDUACAN','EMILIANO ZAPATA','HUIMANGUILLO','JALAPA','JALPA DE MENDEZ','JONUTA','MACUSPANA','NACAJUCA','PARAISO','TACOTALPA','TEAPA','TENOSIQUE') 

var provincias_28=new Array("-",'ABASOLO','ALDAMA','ALTAMIRA','ANTIGUO MORELOS','BURS','BUSTAMANTE','CAMAR','CASAS','CIUDAD MADERO','CRUILLAS','MEZ FARIAS','NZALEZ','GUEMEZ','GUERRERO','GUSTAVO DIAZ ORDAZ','HIDAL','JAUMAVE','JIMENEZ','LLERA','MAINERO','EL MANTE','MATAMOROS','MENDEZ','MIER','MIGUEL ALEMAN','MIQUIHUANA','NUEVO LAREDO','NUEVO MORELOS','OCAMPO','PADILLA','PALMILLAS','REYNOSA','RIO BRAVO','SAN CARLOS','SAN FERNANDO','SAN NICOLAS','SOTO LA MARINA','TAMPICO','TULA','VALLE HERMOSO','VICTORIA','VILLAGRAN','XICOTENCATL')

var provincias_29=new Array("-",'AMAXAC DE GUERRERO','APETATITLAN DE A. CARVAJAL','ATLANGATEPEC','ALTZAYANCA','APIZACO','CALPULALPAN','EL CARMEN TEQUEXQUITLA','CUAPIAXTLA','CUAXOMULCO','CHIAUTEMPAN','MUÑOZ DE DOMIN ARENAS','ESPAÑITA','HUAMANTLA','HUEYOTLIPAN','IXTACUIXTLA DE M. MATAMOROS','IXTENCO','MAZATECOCHCO DE J. M. MORELOS','CONTLA DE JUAN CUAMATZI','TEPETITLA DE LARDIZABAL','SANCTORUM DE LAZARO CARDENAS','NANACAMILPA DE MARIANO ARISTA','ACUAMANALA DE MIGUEL HIDAL','NATIVITAS','PANOTLA','SAN PABLO DEL MONTE','SANTA CRUZ TLAXCALA','TENANCIN','TEOLOCHOLCO','TEPEYANCO','TERRENATE','TETLA DE LA SOLIDARIDAD','TETLATLAHUCA','TLAXCALA','TLAXCO','TOCATLAN','TOTOLAC','ZITLALTEPEC DE T. SANCHEZ S.','TZOMPANTEPEC','XALOZTOC','XALTOCAN','PAPALOTLA DE XICOHTENCATL','XICOHTZINCO','YAUHQUEMECAN','ZACATELCO','BENITO JUAREZ','EMILIANO ZAPATA','LAZARO CARDENAS','LA MAGDALENA TLALTELULCO','SAN DAMIAN TEXOLOC','SAN FRANCISCO TETLANOHCAN','SAN JERONIMO ZACUALPAN','SAN JOSE TEACALCO','SAN JUAN HUACTZINCO','SAN LORENZO AXOCOMANITLA','SAN LUCAS TECOPILCO','SANTA ANA NOPALUCAN','SANTA APOLONIA TEACALCO','SANTA CATARINA AYOMETLA','SANTA CRUZ QUILEHTLA','SANTA ISABEL XILOXOXTLA') 

var provincias_30=new Array("-",'ACAJETE','ACATLAN','ACAYUCAN','ACTOPAN','ACULA','ACULTZIN','CAMARON DE TEJEDA','ALPATLAHUAC','ALTO LUCERO DE GUTIERREZ B.','ALTOTONGA','ALVARADO','AMATITLAN','NARANJOS AMATLAN','AMATLAN DE LOS REYES','ANGEL R. CABADA','LA ANTIGUA','APAZAPAN','AQUILA','ASTACINGA','ATLAHUILCO','ATOYAC','ATZACAN','ATZALAN','TLALTETELA','AYAHUALULCO','BANDERILLA','BENITO JUAREZ','BOCA DEL RIO','CALCAHUALCO','CAMERINO Z. MENDOZA','CARRILLO PUERTO','CATEMACO','CAZONES','CERRO AZUL','CITLALTEPETL','COACOATZINTLA','COAHUITLAN','COATEPEC','COATZACOALCOS','COATZINTLA','COETZALA','COLIPA','COMAPA','CORDOBA','COSAMALOAPAN DE CARPIO','COSAUTLAN DE CARVAJAL','COSCOMATEPEC','COSOLEACAQUE','COTAXTLA','COXQUIHUI','COYUTLA','CUICHAPA','CUITLAHUAC','CHACALTIANGUIS','CHALMA','CHICONAMEL','CHICONQUIACO','CHICONTEPEC','CHINAMECA','CHINAMPA DE ROSTIZA','LAS CHOAPAS','CHOCAMAN','CHONTLA','CHUMATLAN','EMILIANO ZAPATA','ESPINAL','FILOMENO MATA','FORTIN','GUTIERREZ ZAMORA','HIDALTITLAN','HUATUSCO','HUAYACOCOTLA','HUEYAPAN DE OCAMPO','HUILOAPAN','IGNACIO DE LA LLAVE','ILAMATLAN','ISLA','IXCATEPEC','IXHUACAN DE LOS REYES','IXHUATLAN DEL CAFE','IXHUATLANCILLO','IXHUATLAN DEL SURESTE','IXHUATLAN DE MADERO','IXMATLAHUACAN','IXTACZOQUITLAN','JALACIN','XALAPA','JALCOMULCO','JALTIPAN','JAMAPA','JESUS CARRANZA','XICO','JILOTEPEC','JUAN RODRIGUEZ CLARA','JUCHIQUE DE FERRER','LANDERO Y COSS','LERDO DE TEJADA','MAGDALENA','MALTRATA','MANLIO FABIO ALTAMIRANO','MARIANO ESCOBEDO','MARTINEZ DE LA TORRE','MECATLAN','MECAYAPAN','MEDELLIN','MIAHUATLAN','LAS MINAS','MINATITLAN','MISANTLA','MIXTLA DE ALTAMIRANO','MOLOACAN','NAOLINCO','NARANJAL','NAUTLA','NOGALES','OLUTA','OMEALCA','ORIZABA','OTATITLAN','OTEAPAN','OZULUAMA DE MASCAREÑAS','PAJAPAN','PANUCO','PAPANTLA','PASO DEL MACHO','PASO DE OVEJAS','LA PERLA','PEROTE','PLATON SANCHEZ','PLAYA VICENTE','POZA RICA DE HIDAL','LAS VIGAS DE RAMIREZ','PUEBLO VIEJO','PUENTE NACIONAL','RAFAEL DELGADO','RAFAEL LUCIO','LOS REYES','RIO BLANCO','SALTABARRANCA','SAN ANDRES TENEJAPAN','SAN ANDRES TUXTLA','SAN JUAN EVANGELISTA','SANTIA TUXTLA','SAYULA DE ALEMAN','SOCONUSCO','SOCHIAPA','SOLEDAD ATZOMPA','SOLEDAD DE DOBLADO','SOTEAPAN','TAMALIN','TAMIAHUA','TAMPICO ALTO','TANCOCO','TANTIMA','TANTOYUCA','TATATILA','CASTILLO DE TEAYO','TECOLUTLA','TEHUIPAN','TEMAPACHE','TEMPOAL','TENAMPA','TENOCHTITLAN','TEOCELO','TEPATLAXCO','TEPETLAN','TEPETZINTLA','TEQUILA','JOSE AZUETA','TEXCATEPEC','TEXHUACAN','TEXISTEPEC','TEZONAPA','TIERRA BLANCA','TIHUATLAN','TLACOJALPAN','TLACOLULAN','TLACOTALPAN','TLACOTEPEC DE MEJIA','TLACHICHILCO','TLALIXCOYAN','TLALNELHUAYOCAN','TLAPACOYAN','TLAQUILPA','TLILAPAN','TOMATLAN','TONAYAN','TOTUTLA','TUXPAM','TUXTILLA','URSULO GALVAN','VEGA DE ALATORRE','VERACRUZ','VILLA ALDAMA','XOXOCOTLA','YANGA','YECUATLA','ZACUALPAN','ZARAZA','ZENTLA','ZONLICA','ZONTECOMATLAN DE LOPEZ Y F.','ZOZOCOLCO DE HIDAL','AGUA DULCE','EL HI','NANCHITAL DE LAZARO CARDENAS','TRES VALLES','CARLOS A. CARRILLO','TATAHUICAPAN DE JUAREZ','UXPANAPA') 

var provincias_31=new Array("-",'ABALA','ACANCEH','AKIL','BACA','BOKOBA','BUCTZOTZ','CACALCHEN','CALOTMUL','CANSAHCAB','CANTAMAYEC','CELESTUN','CENOTILLO','CONKAL','CUNCUNUL','CUZAMA','CHACSINKIN','CHANKOM','CHAPAB','CHEMAX','CHICXULUB PUEBLO','CHICHIMILA','CHIKINDZONOT','CHOCHOLA','CHUMAYEL','DZAN','DZEMUL','DZIDZANTUN','DZILAM DE BRAVO','DZILAM NZALEZ','DZITAS','DZONCAUICH','ESPITA','HALACHO','HOCABA','HOCTUN','HOMUN','HUHI','HUNUCMA','IXIL','IZAMAL','KANASIN','KANTUNIL','KAUA','KINCHIL','KOPOMA','MAMA','MANI','MAXCANU','MAYAPAN','MERIDA','MOCOCHA','MOTUL','MUNA','MUXUPIP','OPICHEN','OXKUTZCAB','PANABA','PETO','PROGRESO','QUINTANA ROO','RIO LAGARTOS','SACALUM','SAMAHIL','SANAHCAT','SAN FELIPE','SANTA ELENA','SEYE','SINANCHE','SOTUTA','SUCILA','SUDZAL','SUMA','TAHDZIU','TAHMEK','TEABO','TECOH','TEKAL DE VENEGAS','TEKANTO','TEKAX','TEKIT','TEKOM','TELCHAC PUEBLO','TELCHAC PUERTO','TEMAX','TEMOZON','TEPAKAN','TETIZ','TEYA','TICUL','TIMUCUY','TINUM','TIXCACALCUPUL','TIXKOKOB','TIXMEHUAC','TIXPEHUAL','TIZIMIN','TUNKAS','TZUCACAB','UAYMA','UCU','UMAN','VALLADOLID','XOCCHEL','YAXCABA','YAXKUKUL','YOBAIN') 

var provincias_32=new Array("-",'APOZOL','APULCO','ATOLINGA','BENITO JUAREZ','CALERA','CAÑITAS DE FELIPE PESCADOR','CONCEPCION DEL ORO','CUAUHTEMOC','CHALCHIHUITES','FRESNILLO','TRINIDAD GARCIA DE LA CADENA','GENARO CODINA','GENERAL ENRIQUE ESTRADA','GENERAL FRANCISCO R. MURGUIA','EL PLATEADO DE JOAQUIN AMARO','GENERAL PANFILO NATERA','GUADALUPE','HUANUSCO','JALPA','JEREZ','JIMENEZ DEL TEUL','JUAN ALDAMA','JUCHIPILA','LORETO','LUIS MOYA','MAZAPIL','MELCHOR OCAMPO','MEZQUITAL DEL ORO','MIGUEL AUZA','MOMAX','MONTE ESCOBEDO','MORELOS','MOYAHUA DE ESTRADA','NOCHISTLAN DE MEJIA','NORIA DE ANGELES','OJOCALIENTE','PANUCO','PINOS','RIO GRANDE','SAIN ALTO','EL SALVADOR','SOMBRERETE','SUSTICACAN','TABASCO','TEPECHITLAN','TEPETON','TEUL DE NZALEZ ORTEGA','TLALTENAN DE SANCHEZ ROMAN','VALPARAISO','VETAGRANDE','VILLA DE COS','VILLA GARCIA','VILLA NZALEZ ORTEGA','VILLA HIDAL','VILLANUEVA','ZACATECAS','TRANCOSO')

 
function cambia_provincia(){ 
   	//tomo el valor del select del pais elegido 
   	var pais 
   	pais = document.solicitud.pais[document.solicitud.pais.selectedIndex].value 
   	//miro a ver si el pais está definido 
   	if (pais != 0) { 
      	//si estaba definido, entonces coloco las opciones de la provincia correspondiente. 
      	//selecciono el array de provincia adecuado 
      	mis_provincias=eval("provincias_" + pais) 
      	//calculo el numero de provincias 
      	num_provincias = mis_provincias.length 
      	//marco el número de provincias en el select 
      	document.solicitud.provincia.length = num_provincias 
      	//para cada provincia del array, la introduzco en el select 
      	for(i=0;i<num_provincias;i++){ 
         	document.solicitud.provincia.options[i].value=mis_provincias[i] 
         	document.solicitud.provincia.options[i].text=mis_provincias[i] 
      	}	
   	}else{ 
      	//si no había provincia seleccionada, elimino las provincias del select 
      	document.solicitud.provincia.length = 1 
      	//coloco un guión en la única opción que he dejado 
      	document.solicitud.provincia.options[0].value = "-" 
      	document.solicitud.provincia.options[0].text = "-" 
   	} 
   	//marco como seleccionada la opción primera de provincia 
   	document.solicitud.provincia.options[0].selected = true 
}





</script>

<style type="text/css">


.up { text-transform:uppercase;}

#cuadro {
	width: 100%;
	
	height:auto;
	margin-right:auto;
	margin-left: auto;
	border-style: dotted; border-width: 1px;
}

table, td, th {    
    border: 1px solid #ddd;
	background-color: #f2f2f2; 
	
}

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}
</style>
</head>



<body>

<form name="solicitud"  method="post" action="http://192.168.39.31/intranet/index.php?option=com_content&view=article&id=65" >
<table width="600px" align="center" cellpadding="10px" bordercolor="#000000"  style=" border-style: solid"  >

<tr>
<td colspan="3">
<?php
if (isset($_SESSION['exito']))
{
echo "<b style='font-size:18px'><center><font color='#FF0000'>".$_SESSION['exito']."</font></center></b>";
} 

else {
	
	echo "";
	
	}
unset($_SESSION['exito']);
?>
</td>
</tr>



<tr>
<td align="right" colspan="2">FOLIO <input type="text" name="folio" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR1']))
	  {
		  echo ($_SESSION['ERROR1']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR1']);
	  ?>
      </b>  
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR2']))
	  {
		  echo ($_SESSION['ERROR2']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR2']);
	  ?>
      </b>
       
</td>
</tr>



<tr>
<td width="200px" align="center"><img src="images/General/logovertical.png" width="120px" height="150px" />
</td>
<td width="400px" align="center"><b>SERVICIO EXTERIOR MEXICANO</b><BR />
<b>CONSULADO GENERAL DE M&Eacute;XICO EN RALEIGH, CAROLINA DEL NORTE</b><BR />
SOLICITUD DE COPIA CERTIFICADA DE ACTA DE NACIMIENTO<BR />EXPEDIDA EN LA REP&Uacute;BLICA MEXICANA
</td>
</tr>


<tr>
<td>&nbsp;</td>
<td align="right">FECHA: <input type="date" name="fecha" min="2016-01-01" max="2030-12-31" step="0">
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR3']))
	  {
		  echo ($_SESSION['ERROR3']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR3']);
	  ?>
      </b>
</td>
</tr>


<tr>
<td>&nbsp;</td>
<td align="right">NO. DE SOLICITUD: <input type="text" name="solicitud" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR4']))
	  {
		  echo ($_SESSION['ERROR4']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR4']);
	  ?>
      </b>
</td>
</tr>

<tr>
<td>&nbsp;</td>
<td align="right">CANTIDAD DE ACTAS: <input type="text" name="cantidad" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR5']))
	  {
		  echo ($_SESSION['ERROR5']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR5']);
	  ?>
      </b>
      
</td>
</tr>

<tr>
<td colspan="2" align="left">IDENTIFICACI&Oacute;N OFICIAL QUE PRESENTA:&nbsp;   
        <select name="identificacion" class="autocomplete">
        <option value=""></option>
        <option value="PASAPORTE">PASAPORTE</option>
        <option value="MATRICULA">MATRICULA</option>
        <option value="IFE">IFE</option>
        <option value="INE">INE</option>
        <option value="LICENCIA DE CONDUCIR">LICENCIA DE CONDUCIR</option>
        <option value="PASAPORTE PADRES">PASAPORTE PADRES</option>
        <option value="FORMATO ICE">FORMATO ICE</option>
        <option value="CERTIFICADO ESCOLAR">CERTIFICADO ESCOLAR</option>
        <option value="ID ESCOLAR">ID ESCOLAR</option>
        </select>
        
        <br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR6']))
	  {
		  echo ($_SESSION['ERROR6']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR6']);
	  ?>
      </b>
</td>
</tr>


<tr>
<td colspan="2" >1.- CURP (SI LA TIENE) <input class="up"  type="text" name="curp" />
<br />
</td>
</tr>


<tr>
<td colspan="2" >2.- NOMBRE COMPLETO <input  class="up" type="text" name="nombre" />

<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR7']))
	  {
		  echo ($_SESSION['ERROR7']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR7']);
	  ?>
      </b>
</td>
</tr>


<tr>
<td colspan="2" >3.- SEXO <select name="sexo" class="autocomplete">
        <option value=""></option>
        <option value="FEMENINO">FEMENINO</option>
        <option value="MASCULINO">MASCULINO</option>
        </select>
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR8']))
	  {
		  echo ($_SESSION['ERROR8']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR8']);
	  ?>
      </b>
</td>        
</tr>


<tr>
<td colspan="2" >4.- ESTADO DE LA REP&Uacute;BLICA DONDE FUE REGISTRADO <select name="estado" class="autocomplete">
<option value=""></option>
<option value="AGUASCALIENTES">AGUASCALIENTES</option>
<option value="BAJA CALIFORNIA">BAJA CALIFORNIA</option>
<option value="BAJA CALIFORNIA SUR">BAJA CALIFORNIA SUR</option>
<option value="CAMPECHE">CAMPECHE</option>
<option value="COAHUILA">COAHUILA</option>
<option value="COLIMA">COLIMA</option>
<option value="CHIAPAS">CHIAPAS</option>
<option value="CHIHUAHUA">CHIHUAHUA</option>
<option value="CIUDAD DE MÉXICO">CIUDAD DE MÉXICO</option>
<option value="DURANGO">DURANGO</option>
<option value="GUANAJUATO">GUANAJUATO</option>
<option value="GUERRERO">GUERRERO</option>
<option value="HIDALGO">HIDALGO</option>
<option value="JALISCO">JALISCO</option>
<option value="MÉXICO">MÉXICO</option>
<option value="MICHOACÁN">MICHOACÁN</option>
<option value="MORELOS">MORELOS</option>
<option value="NAYARIT">NAYARIT</option>
<option value="NUEVO LEÓN">NUEVO LEÓN</option>
<option value="OAXACA">OAXACA</option>
<option value="PUEBLA">PUEBLA</option>
<option value="QUERÉTARO">QUERÉTARO</option>
<option value="QUINTANA ROO">QUINTANA ROO</option>
<option value="SAN LUIS POTOSÍ">SAN LUIS POTOSÍ</option>
<option value="SINALOA">SINALOA</option>
<option value="SONORA">SONORA</option>
<option value="TABASCO">TABASCO</option>
<option value="TAMAULIPAS">TAMAULIPAS</option>
<option value="TLAXCALA">TLAXCALA</option>
<option value="VERACRUZ">VERACRUZ</option>
<option value="YUCATÁN">YUCATÁN</option>
<option value="ZACATECAS">ZACATECAS</option>
        </select>
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR9']))
	  {
		  echo ($_SESSION['ERROR9']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR9']);
	  ?>
      </b>        
</td>        
</tr>

<tr>
<td colspan="2" >5.- LUGAR DE NACIMIENTO 
<select name="pais" onchange="cambia_provincia()"> 
<option value="0" selected>Seleccione... </option>
<option value="1">AGUASCALIENTES</option>
<option value="2">BAJA CALIFORNIA</option>
<option value="3">BAJA CALIFORNIA SUR</option>
<option value="4">CAMPECHE</option>
<option value="5">COAHUILA</option>
<option value="6">COLIMA</option>
<option value="7">CHIAPAS</option>
<option value="8">CHIHUAHUA</option>
<option value="9">CIUDAD DE MÉXICO</option>
<option value="10">DURANGO</option>
<option value="11">GUANAJUATO</option>
<option value="12">GUERRERO</option>
<option value="13">HIDALGO</option>
<option value="14">JALISCO</option>
<option value="15">MÉXICO</option>
<option value="16">MICHOACÁN</option>
<option value="17">MORELOS</option>
<option value="18">NAYARIT</option>
<option value="19">NUEVO LEÓN</option>
<option value="20">OAXACA</option>
<option value="21">PUEBLA</option>
<option value="22">QUERÉTARO</option>
<option value="23">QUINTANA ROO</option>
<option value="24">SAN LUIS POTOSÍ</option>
<option value="25">SINALOA</option>
<option value="26">SONORA</option>
<option value="27">TABASCO</option>
<option value="28">TAMAULIPAS</option>
<option value="29">TLAXCALA</option>
<option value="30">VERACRUZ</option>
<option value="31">YUCATÁN</option>
<option value="32">ZACATECAS</option>
</select>

<select name=provincia> 
<option value="-">- </option>
</select> 

Y  FECHA DE NACIMIENTO<input type="date" name="fechanacimiento" min="1900-01-01" max="2030-12-31" step="0">


<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR10']))
	  {
		  echo ($_SESSION['ERROR10']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR10']);
	  ?>
      </b> 


<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR11']))
	  {
		  echo ($_SESSION['ERROR11']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR11']);
	  ?>
      </b> 


<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR12']))
	  {
		  echo ($_SESSION['ERROR12']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR12']);
	  ?>
      </b>
</td>        
</tr>




<tr>
<td colspan="2" >6.- NOMBRES Y APELLIDOS DE LOS PADRES<br /><br />
a. PADRE <input class="up" type="text" name="padre" /><br /><br />
b. MADRE <input class="up" type="text" name="madre" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR13']))
	  {
		  echo ($_SESSION['ERROR13']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR13']);
	  ?>
      </b> 
      
      <br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR14']))
	  {
		  echo ($_SESSION['ERROR14']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR14']);
	  ?>
      </b> 
</td>
</tr>



<tr>
<td colspan="2" >7.- DOMICILIO ACTUAL <input class="up" type="text" name="domicilio" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR15']))
	  {
		  echo ($_SESSION['ERROR15']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR15']);
	  ?>
      </b> 
</td>
</tr>



<tr>
<td colspan="2" >8.- N&Uacute;MERO DE TEL&Eacute;FONO (FIJO O CELULAR) <input type="tel" name="telefono" pattern="[0-9]{10}" />
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR16']))
	  {
		  echo ($_SESSION['ERROR16']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR16']);
	  ?>
      </b> 


</td>
</tr>


<tr>
<td colspan="2" >9.- CORREO ELECTR&Oacute;NICO <input type="email" name="email" pattern="[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{1,5}">
<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR17']))
	  {
		  echo ($_SESSION['ERROR17']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR17']);
	  ?>
      </b> 


</td>
</tr>



<tr>
<td width="300px" align="center" ><select name="pspi" class="autocomplete">
        <option value=""></option>
        <option value="BEATRIZ VEL&Aacute;ZQUEZ">BEATRIZ VELAZQUEZ</option>
        <option value="EMMA PERIAN">EMMA PERIAN</option>  
        <option value="DENISSE TORRES">DENISSE TORRES</option>          
        <option value="ANGELA ESPINOZA">ANGELA ESPINOZA</option>  
        <option value="JONATHAN GONZALEZ">JONATHAN GONZALEZ</option>            
        </select><BR /><BR />
        PSPI QUE REALIZA EL TR&Aacute;MITE 
        <br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR19']))
	  {
		  echo ($_SESSION['ERROR19']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR19']);
	  ?>
      </b> 
        
        
        
        
        
        </td>
        
<td width="300px"align="center" ><select name="sem" class="autocomplete">
        <option value=""></option>
        <option value="REMEDIOS GOMEZ ARNAU">REMEDIOS GOMEZ ARNAU</option>
        <option value="PATRICIA PEREZ GALEANA">PATRICIA PEREZ GALEANA</option>
        <option value="MONICA COLIN">MONICA COLIN</option>
        <option value="JACOBO TELLEZ">JACOBO TELLEZ</option>
        <option value="CARLOS OSNAYA">CARLOS OSNAYA</option>
        <option value="LUIS LOPEZ">LUIS LOPEZ</option>
        <option value="ADRIANA VILLARREAL">ADRIANA VILLARREAL</option>
        <option value="HILDA LUGO">HILDA LUGO</option>
        <option value="DAVID ESCOBAR">DAVID ESCOBAR</option>
        <option value="FRANCISCO GUZMAN">FRANCISCO GUZMAN</option>
        </select><BR /><BR />
AUTORIZACI&Oacute;N DEL SUPERVISOR PARA IMPRESI&Oacute;N

<br />
      <b style="color: #090">
      <?php	 
	  if (isset($_SESSION['ERROR18']))
	  {
		  echo ($_SESSION['ERROR18']);
	  } 
	  
	  else {		  
		  echo "";	  
	  }
	  
	  unset ($_SESSION['ERROR18']);
	  ?>
      </b> 
</td>
</tr>



<tr>
  <td colspan="4" align="right">
 
  
  
  <input type="reset" value="Borrar información">&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" name="Guardar" value="Guardar"></td>
  </tr>
    
</table>

</form>




























</body>
</html>